src/Entity/Article.php
<?php

namespace App\Entity;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @Vich\Uploadable
 */
class Article
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="imageFileName")
     * @var File
     */

    private $imageFile;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="article", cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="article")
     */
    private $user;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }


    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }


    public function getAuthor(): User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): void
    {
        $this->author = $author;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath()
    {
        return 'images/' . $this->getImageFilename();
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        $criteria = Criteria::create()
            ->andWhere(Criteria::expr()->eq('isDeleted', false))
            ->orderBy(['createdAt' => 'DESC']);
        return $this->comments->matching($criteria);

    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     * @throws \Exception
     */
    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;

        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }




}

src/Form/ArticleType.php
<?php


namespace App\Form;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\File\File;
use App\Entity\Article;
use App\Form\Type\TagsInputType;
use Symfony\Component\Form\AbstractType;
use App\Form\Type\DateTimePickerType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class ArticleType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('title', null, [
                'attr' => ['autofocus' => true],
                'label' => 'Title',
            ])
            ->add('content', null, [
                'attr' => ['rows' => 10],
                'help' => 'Yours article content...',
                'label' => 'Article Content',
            ])
            ->add('imageFile', FileType::class, array(
                'label'=>"Insert Image",

            ))

            ->add('publishedAt', DateTimePickerType::class, [
                'label' => 'Publish Date',
                'help' => 'Set the date in the future to schedule the blog article publication.',
            ])
            ->add('tags', TagsInputType::class, [
                'label' => ' Article Tag',
                'required' => false,
            ])

        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Entity\Tag;
use App\Events;
use App\Form\ArticleType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Form\CommentType;
use App\Repository\ArticleRepository;
use App\Service\MarkdownHelper;
use App\Service\SlackClient;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use App\Utils\Slugger;
use App\DataFixtures\ArticleFixtures;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\EventDispatcher\GenericEvent;

class ArticleController extends AbstractController
{
    /**
     * Currently unused: just showing a controller with a constructor!
     */
    private $isDebug;


    public function __construct(bool $isDebug)
    {
        $this->isDebug = $isDebug;


    }



    /**
     * @Route("/", name="app_homepage")
     */
    public function homepage(ArticleRepository $repository)
    {
        //$repository = $em->getRepository(Article::class);

        $articles = $repository->findAllPublishedOrderedByNewest();//Bütün article'ları articles dizisinde tutuyor.
        return $this->render('article/homepage.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/news/{slug}", name="article_show")
     * @ParamConverter("article", class="App\Entity\Article")
     */

    public function show(Article $article, SlackClient $slack, EntityManagerInterface $entityManager, Request $request)
    {
        if ($article->getSlug() == 'khaaaaaan') {
            $slack->sendMessage('Kahn', 'Ah, Kirk, my old friend...');
        }
        if (!$article) {
            throw $this->createNotFoundException(sprintf('No article for slug "%s"', $article->getSlug()));
        }

        $comment = new Comment();
        $commentForm = $this->createForm(CommentType::class, $comment);

        $commentForm->handleRequest($request);
        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setIpadress($request->getClientIp());
            $comment->setIsDeleted(false);
            $comment->setArticle($article);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);

            $entityManager->flush();
            return $this->render('article/show.html.twig', array(
                'commentForm' => $commentForm->createView(),
                'article' => $article,

            ));

        }
        $comment = $this->getDoctrine()->getRepository(Comment::class)->findAll();

        return $this->render('article/show.html.twig', array(
            'commentForm' => $commentForm->createView(),
            'article' => $article,

        ));
    }


    /**
     * @Route("/news/{slug}/heart", name="article_toggle_heart")
     *
     */

    public function toggleArticleHeart(Article $article, LoggerInterface $logger, EntityManagerInterface $entityManager)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $heartCount = $article->incrementHeartCount();
        $entityManager->persist($heartCount);
        $entityManager->flush();
        return new JsonResponse(['hearts' => $article->getHeartCount()]);

    }


    /**
     * @Route("/user/article/new", name="user_article_new")
     */

    public function new(Request $request, EventDispatcherInterface $eventDispatcher): Response
    {
        $article = new Article();
        $user = $this->getUser();
        $article->setAuthor($user);

        if (is_null($user)) {
            // throw $this->createAccessDeniedException('Access Denied.');
            $this->addFlash('notice', 'To create an article, you must first log in.');
            return $this->redirectToRoute('app_homepage');
        }


        $form = $this->createForm(ArticleType::class, $article)
            ->add('saveAndCreateNew', SubmitType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * var UploadFile $file;
             */
            $file = $article->getImageFile();
            $imageFilename = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move(
                $this->getParameter('images_directory'), $imageFilename
            );
            $article->setImageFilename($imageFilename);
            $article->setSlug(Slugger::slugify($article->getTitle()));

            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            $this->addFlash('succes', 'Your article created successfully.');

            $event = new GenericEvent($article); // yeni bir event oluşturduk bizim article mızın oluşturulmasına göre tetiklenerek çalışmaya başlayacak.
            $eventDispatcher->dispatch(Events::ARTICLE_CREATED, $event);

            if ($form->get('saveAndCreateNew')->isClicked()) {
                return $this->redirectToRoute('app_homepage');
            }

            return $this->redirectToRoute('user_article_new');
        }

        return $this->render('article/new_article.html.twig', [
            'article' => $article,
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

}

templates/article/homepage.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="container">
        <div class="row">

            <!-- Article List -->

            <div class="col-sm-12 col-md-8">


                <!-- H1 Article -->
                <a class="main-article-link" href="#">
                    <div class="main-article mb-5 pb-3">
                        <img src="{{ asset('images/meteor-shower.jpg') }}" alt="meteor shower">
                        <h1 class="text-center mt-2">Ursid Meteor Shower: <br>Healthier than a regular shower?</h1>
                    </div>
                </a>

                <!-- Supporting Articles -->


                {% for article in articles %}
                    <div>
                        {% for message in app.flashes('notice') %}
                            <div class="alert alert-warning">
                                <strong>Warning!</strong>
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                    {% for message in app.flashes('succes') %}
                        <div class="alert alert-success">
                            <strong>Success!</strong>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                    <div class="article-container my-1">
                        <a href="{{ path('article_show', {slug: article.slug}) }}">
                            <img class="article-img" src="{{ asset(article.imagePath) }}">
                            <div class="article-title d-inline-block pl-3 align-middle">
                                <span>{{ article.title }}</span>
                                <small>({{ article.nonDeletedComments|length }} comments)</small>
                                <br>
                                {% for tag in article.tags %}
                                    <small>
                                        <span class="badge badge-light">{{ tag.name }}</span>


                                    </small>
                                {% endfor %}
                                <br>
                                <span class="align-left article-details"><img class="article-author-img rounded-circle"
                                                                              src="{{ asset('images/alien-profile.png') }}"> {{ article.author.username }} </span>
                                <span class="pl-5 article-details float-right"> {{ article.publishedAt ? article.publishedAt|ago }}</span>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>

            <!-- Right bar ad space -->


            <div class="col-sm-12 col-md-4 text-center">
                <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                    <img class="advertisement-img" src="{{ asset('images/space-ice.png') }}">
                    <p><span class="advertisement-text">New:</span> Space Ice Cream!</p>
                    <button class="btn btn-info">Buy Now!</button>
                </div>

                <div class="quote-space pb-2 pt-2 px-5">
                    <h3 class="text-center pb-3">Trending Quotes</h3>
                    <p><i class="fa fa-comment"></i> "Our two greatest problems are gravity and paperwork. We can lick
                        gravity, but sometimes the paperwork is overwhelming." <br>— <a
                                href="https://en.wikipedia.org/wiki/Wernher_von_Braun">Wernher von Braun, Rocket
                            Engineer</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "Let's face it, space is a risky business. I always
                        considered every launch a barely controlled explosion." <br>— <a
                                href="https://en.wikipedia.org/wiki/Aaron_Cohen_(Deputy_NASA_administrator)">Aaron
                            Cohen, NASA Administrator</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "If offered a seat on a rocket ship, don't ask what
                        seat. Just get on."<br>— <a href="https://en.wikipedia.org/wiki/Christa_McAuliffe">Christa
                            McAuliffe, Challenger Astronaut</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/new_article.html.twig
{# templates/registration/register.html.twig #}

{% extends 'base.html.twig' %}

{% block title %} Create New Article For SpaceBar {% endblock %}
 {% block body %}
     <div class="container">
         <div class="row">


             <div class="col-sm-12 col-md-8">

                 {{ form_start(form) }}
                 {{ form_widget(form)}}
                 {{ form_end(form) }}
             </div>
         </div>
     </div>
 {% endblock %}

templates/article/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}Read: {{ article.title }}{% endblock %}

{% block content_body %}
    <div class="row">
        <div class="col-sm-12">
            <img class="show-article-img" src="{{ asset(article.imagePath) }}">
            <div class="show-article-title-container d-inline-block pl-3 align-middle">
                <span class="show-article-title ">{{ article.title }}</span>
                <br>
                <span class="align-left article-details"><img class="article-author-img rounded-circle"
                                                              src="{{ asset('images/alien-profile.png') }}"> {{ article.author.username }} </span>
                <span class="pl-2 article-details">
                    {{ article.publishedAt ? article.publishedAt|ago : 'unpublished' }}
                </span>
                <span class="pl-2 article-details">
                    <span class="js-like-article-count">{{ article.heartCount }}</span>
                    <a href="{{ path('article_toggle_heart', {slug: article.slug}) }}"
                       class="fa fa-heart-o like-article js-like-article"></a>
                </span>
                <span class="pl-2 article-details">
                    {% for tag in article.tags %}
                    {% endfor %}
                </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="article-text">
                {{ article.content|cached_markdown }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <p class="share-icons mb-5"><span class="pr-1">Share:</span> <i class="pr-1 fa fa-facebook-square"></i><i
                        class="pr-1 fa fa-twitter-square"></i><i class="pr-1 fa fa-reddit-square"></i><i
                        class="pr-1 fa fa-share-alt-square"></i></p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h3><i class="pr-3 fa fa-comment"></i>{{ article.nonDeletedComments|length }} Comments</h3>
            <hr>

            <div class="row mb-5">
                <div class="col-sm-12">
                    <img class="comment-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}">
                    <div class="comment-container d-inline-block pl-3 align-top">
                        {{ form_start(commentForm) }}
                        {{ form_widget(commentForm) }}
                        {{ form_end(commentForm) }}
                    </div>
                </div>
            </div>

            <div>

            </div>

            <div>


            </div>


            {% for comment in article.nonDeletedComments %}
                <div class="row">
                    <div class="col-sm-12">
                        <img class="comment-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">
                        <div class="comment-container d-inline-block pl-3 align-top">
                            <span class="commenter-name">{{ comment.authorName }}</span>
                            <small>about {{ comment.createdAt|ago }}</small>
                            {% if comment.isDeleted %}
                                <span class="fa fa-close"></span> deleted
                            {% endif %}
                            <br>
                            <span class="comment"> {{ comment.content }}</span>
                            <p><a href="#">Reply</a></p>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="{{ asset('js/article_show.js') }}"></script>
{% endblock %}